### ISSUE TITLE
get_message_status 失效

### ISSUE THREAD

**Issue by tka** [guanting112/twsms2#1]
目前 get_message_status 會讀取 `https://api.twsms.com:443/smsQuery.php?msgid=220755036&username=FOO&password=BAR` 的網址來取得發送狀態

但是 TWSMS 需要加傳遞發送時的時手機號碼, 也就是

`https://api.twsms.com:443/smsQuery.php?mobile=0900000000&msgid=220755036&username=FOO&password=BAR` 

才能正確讀取

**Comment by tka** [comment]
抱歉, 沒問題, 是我參數打錯, 所以生錯網址

**Comment by guanting112** [comment]
ＯＫＯＫ有解決就好，也感謝您對 twsms2 的使用喔！:D
